Insert into tbl_estado (id_estado,estado) values (12, 'Acre');
Insert into tbl_estado (id_estado,estado) values (16, 'Amapá');
Insert into tbl_estado (id_estado,estado) values (13, 'Amazonas');
Insert into tbl_estado (id_estado,estado) values (23, 'Ceará');
Insert into tbl_estado (id_estado,estado) values (53, 'Distrito Federal');
Insert into tbl_estado (id_estado,estado) values (32, 'Espírito Santo');
Insert into tbl_estado (id_estado,estado) values (52, 'Goiás');
Insert into tbl_estado (id_estado,estado) values (21, 'Maranhão');
Insert into tbl_estado (id_estado,estado) values (51, 'Mato Grosso');
Insert into tbl_estado (id_estado,estado) values (50, 'Mato Grosso do Sul');
Insert into tbl_estado (id_estado,estado) values (15, 'Pará');
Insert into tbl_estado (id_estado,estado) values (25, 'Paraíba');
Insert into tbl_estado (id_estado,estado) values (41, 'Paraná');
Insert into tbl_estado (id_estado,estado) values (22, 'Piauí');
Insert into tbl_estado (id_estado,estado) values (33, 'Rio de Janeiro');
Insert into tbl_estado (id_estado,estado) values (24, 'Rio Grande do Norte');
Insert into tbl_estado (id_estado,estado) values (43, 'Rio Grande do Sul');
Insert into tbl_estado (id_estado,estado) values (11, 'Rondônia');
Insert into tbl_estado (id_estado,estado) values (14, 'Roraima');
Insert into tbl_estado (id_estado,estado) values (42, 'Santa Catarina');
Insert into tbl_estado (id_estado,estado) values (28, 'Sergipe');
Insert into tbl_estado (id_estado,estado) values (17, 'Tocantins');